# Задание 1

Создайте numpy array с элементами от числа N до 0.

In [1]:
import numpy as np

In [2]:
a = np.arange(35 - 1, 0 - 1, -1)
a

array([34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18,
       17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,
        0])

# Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
a = (np.arange(35 - 1, 0 - 1, -1)).reshape(7,5)
a

array([[34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [4]:
b = np.diag(a, k = -4)
b

array([14,  8,  2])

In [5]:
sum(b)

24

# Задание 3

Решите систему уравнений:


4x + 2y + z = 4


x + 3y = 12


5y + 4z = -3

In [6]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [7]:
[round(x, 4) for x in np.linalg.solve(a, b)]

[0.4667, 3.8444, -5.5556]

# Задание 4

Найдите самого похожего пользователя.

In [8]:
def cosine( a, b ):
    alenght = np.linalg.norm(a)
    blenght = np.linalg.norm(b)
    return np.dot(a, b)/(alenght * blenght)

In [9]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [10]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [11]:
coses = {k:cosine(v, next_user_stats) for k, v in enumerate(users_stats)}
coses

{0: 0.19999999999999996,
 1: 0.8451542547285165,
 2: 0.3999999999999999,
 3: 0.7905694150420948,
 4: 0.3999999999999999,
 5: 0.0,
 6: 0.0,
 7: 0.9486832980505138,
 8: 0.0,
 9: 0.0}

In [12]:
m = max(coses, key = coses.get)
m

7

# Задание 5

Определите, какому фильму было выставлено больше всего оценок 5.0.

In [13]:
import pandas as pd

In [14]:
pd.set_option('display.notebook_repr_html', False)
pd.set_option('display.max_columns', 8)
pd.set_option('display.max_rows', 50)
pd.set_option('display.width', 80)

In [15]:
movies=pd.read_csv("movies.csv")
links=pd.read_csv("links.csv")
ratings=pd.read_csv("ratings.csv")
tags=pd.read_csv("tags.csv")

In [16]:
movies.head(2)

   movieId             title                                       genres
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
1        2    Jumanji (1995)                   Adventure|Children|Fantasy

In [17]:
links.head(2)

   movieId  imdbId  tmdbId
0        1  114709   862.0
1        2  113497  8844.0

In [18]:
ratings.head(2)

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247

In [19]:
tags.head(2)

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996

### Работаем с ratings, потом по ключу определяем название фильма.

In [20]:
ratings[ratings.rating == 5].head(2)

   userId  movieId  rating  timestamp
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [21]:
count = dict(ratings[ratings.rating == 5].movieId.value_counts())
count

{318: 153,
 296: 123,
 356: 116,
 2571: 109,
 260: 104,
 593: 92,
 527: 92,
 858: 88,
 2959: 81,
 1196: 80,
 110: 80,
 50: 71,
 1198: 69,
 1210: 65,
 2858: 65,
 589: 64,
 4993: 62,
 2028: 61,
 608: 57,
 1197: 55,
 7153: 53,
 47: 52,
 1136: 51,
 58559: 49,
 1270: 49,
 5952: 49,
 1221: 48,
 1: 47,
 457: 46,
 541: 46,
 32: 45,
 1208: 45,
 1089: 45,
 150: 45,
 4973: 43,
 3578: 43,
 4226: 42,
 912: 41,
 79132: 41,
 1193: 41,
 364: 40,
 1213: 40,
 480: 40,
 1200: 38,
 2762: 36,
 1214: 36,
 750: 36,
 1206: 36,
 590: 35,
 293: 35,
 2324: 35,
 588: 35,
 924: 34,
 1704: 34,
 7361: 33,
 2329: 33,
 904: 32,
 1265: 32,
 1732: 32,
 111: 32,
 1291: 31,
 1387: 31,
 595: 31,
 4306: 30,
 1036: 29,
 1258: 29,
 1222: 28,
 3147: 28,
 1097: 28,
 60069: 27,
 1073: 27,
 34: 27,
 780: 26,
 48516: 26,
 919: 26,
 377: 26,
 4878: 25,
 3949: 25,
 68954: 25,
 4011: 25,
 1617: 25,
 1225: 25,
 380: 24,
 1201: 24,
 1247: 24,
 6: 24,
 778: 24,
 1080: 23,
 1240: 23,
 165: 23,
 1199: 23,
 5618: 23,
 223: 23,
 2997: 23,
 

In [22]:
max5rating_filmId = max(count, key = count.get)
max5rating_filmId

318

In [23]:
movies[movies.movieId == max5rating_filmId]

     movieId                             title       genres
277      318  Shawshank Redemption, The (1994)  Crime|Drama

# Задание 6

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Latvia, Lithuania, Estonia) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [24]:
power=pd.read_csv("power.csv")
power

          country  year  quantity  category
0         Austria  1996       5.0         1
1         Austria  1995      17.0         1
2         Belgium  2014       0.0         1
3         Belgium  2013       0.0         1
4         Belgium  2012      35.0         1
...           ...   ...       ...       ...
1189477  Viet Nam  2012      92.0        71
1189478  Viet Nam  2011      87.0        71
1189479  Viet Nam  2010      50.0        71
1189480  Viet Nam  2009      10.0        71
1189481  Viet Nam  2008       1.0        71

[1189482 rows x 4 columns]

In [25]:
pp_filter1 = power['country'].isin(['Latvia', 'Lithuania', 'Estonia'])
power_countries = power[pp_filter1]
p_c = power_countries
p_c

           country  year  quantity  category
373      Lithuania  2014      39.0         1
374      Lithuania  2013     192.0         1
375      Lithuania  2012     196.0         1
376      Lithuania  2011     171.0         1
377      Lithuania  2010     158.0         1
...            ...   ...       ...       ...
1188862  Lithuania  2003       0.0        71
1188863  Lithuania  2002       0.0        71
1188864  Lithuania  2001       0.0        71
1188865  Lithuania  2000       0.0        71
1188866  Lithuania  1999       0.0        71

[27306 rows x 4 columns]

In [26]:
pp_filter2 = p_c['category'].isin([4, 12, 21])
power_category_countries = p_c[pp_filter2]
p_c_c = power_category_countries
p_c_c

          country  year  quantity  category
10617     Estonia  2008       1.0         4
10618     Estonia  2007       0.0         4
10619     Estonia  2006       0.0         4
10620     Estonia  2005       1.0         4
10621     Estonia  2004       1.0         4
...           ...   ...       ...       ...
253986  Lithuania  2005       1.0        21
253987  Lithuania  2004       1.0        21
253988  Lithuania  2003       0.0        21
253989  Lithuania  2002       0.0        21
253990  Lithuania  2001       0.0        21

[1253 rows x 4 columns]

In [27]:
power_quantity_category_countries = p_c_c[p_c_c.quantity >= 0]
p_q_c_c = power_quantity_category_countries
p_q_c_c

          country  year  quantity  category
10617     Estonia  2008       1.0         4
10618     Estonia  2007       0.0         4
10619     Estonia  2006       0.0         4
10620     Estonia  2005       1.0         4
10621     Estonia  2004       1.0         4
...           ...   ...       ...       ...
253986  Lithuania  2005       1.0        21
253987  Lithuania  2004       1.0        21
253988  Lithuania  2003       0.0        21
253989  Lithuania  2002       0.0        21
253990  Lithuania  2001       0.0        21

[1245 rows x 4 columns]

In [28]:
temp2005 = p_q_c_c[p_q_c_c.year >= 2005]
power_quantity_category_countries_years = temp2005[temp2005.year <= 2010]
p_q_c_c_y = power_quantity_category_countries_years
p_q_c_c_y

          country  year  quantity  category
10617     Estonia  2008       1.0         4
10618     Estonia  2007       0.0         4
10619     Estonia  2006       0.0         4
10620     Estonia  2005       1.0         4
11156   Lithuania  2008       1.0         4
...           ...   ...       ...       ...
253982  Lithuania  2009      98.0        21
253983  Lithuania  2008      54.0        21
253984  Lithuania  2007      47.0        21
253985  Lithuania  2006      31.0        21
253986  Lithuania  2005       1.0        21

[408 rows x 4 columns]

In [29]:
p_q_c_c_y.quantity.sum()

240580.0